server:
  port: 8091
spring:
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lyc
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 10000
  application:
    name: soa
  management:
    endpoints:
      web:
        exposure:
          include: health,info,loggers
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka
